/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeciesRouteImport } from './routes/species'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PlantsRouteImport } from './routes/plants'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotificationSettingsRouteImport } from './routes/notification-settings'
import { Route as MapRouteImport } from './routes/map'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlantsIdRouteImport } from './routes/plants.$id'
import { Route as PlantNewRouteImport } from './routes/plant.new'
import { Route as PlantsIdUpdateRouteImport } from './routes/plants.$id.update'
import { Route as PlantsIdCareRouteImport } from './routes/plants.$id.care'

const SpeciesRoute = SpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsRoute = PlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationSettingsRoute = NotificationSettingsRouteImport.update({
  id: '/notification-settings',
  path: '/notification-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsIdRoute = PlantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlantsRoute,
} as any)
const PlantNewRoute = PlantNewRouteImport.update({
  id: '/plant/new',
  path: '/plant/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsIdUpdateRoute = PlantsIdUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => PlantsIdRoute,
} as any)
const PlantsIdCareRoute = PlantsIdCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => PlantsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/map': typeof MapRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/plants': typeof PlantsRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/species': typeof SpeciesRoute
  '/plant/new': typeof PlantNewRoute
  '/plants/$id': typeof PlantsIdRouteWithChildren
  '/plants/$id/care': typeof PlantsIdCareRoute
  '/plants/$id/update': typeof PlantsIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/map': typeof MapRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/plants': typeof PlantsRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/species': typeof SpeciesRoute
  '/plant/new': typeof PlantNewRoute
  '/plants/$id': typeof PlantsIdRouteWithChildren
  '/plants/$id/care': typeof PlantsIdCareRoute
  '/plants/$id/update': typeof PlantsIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/map': typeof MapRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/plants': typeof PlantsRouteWithChildren
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/species': typeof SpeciesRoute
  '/plant/new': typeof PlantNewRoute
  '/plants/$id': typeof PlantsIdRouteWithChildren
  '/plants/$id/care': typeof PlantsIdCareRoute
  '/plants/$id/update': typeof PlantsIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/community'
    | '/forgot-password'
    | '/map'
    | '/notification-settings'
    | '/notifications'
    | '/plants'
    | '/preferences'
    | '/profile'
    | '/reset-password'
    | '/species'
    | '/plant/new'
    | '/plants/$id'
    | '/plants/$id/care'
    | '/plants/$id/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/community'
    | '/forgot-password'
    | '/map'
    | '/notification-settings'
    | '/notifications'
    | '/plants'
    | '/preferences'
    | '/profile'
    | '/reset-password'
    | '/species'
    | '/plant/new'
    | '/plants/$id'
    | '/plants/$id/care'
    | '/plants/$id/update'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/auth'
    | '/community'
    | '/forgot-password'
    | '/map'
    | '/notification-settings'
    | '/notifications'
    | '/plants'
    | '/preferences'
    | '/profile'
    | '/reset-password'
    | '/species'
    | '/plant/new'
    | '/plants/$id'
    | '/plants/$id/care'
    | '/plants/$id/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MapRoute: typeof MapRoute
  NotificationSettingsRoute: typeof NotificationSettingsRoute
  NotificationsRoute: typeof NotificationsRoute
  PlantsRoute: typeof PlantsRouteWithChildren
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SpeciesRoute: typeof SpeciesRoute
  PlantNewRoute: typeof PlantNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants': {
      id: '/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof PlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-settings': {
      id: '/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof NotificationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/$id': {
      id: '/plants/$id'
      path: '/$id'
      fullPath: '/plants/$id'
      preLoaderRoute: typeof PlantsIdRouteImport
      parentRoute: typeof PlantsRoute
    }
    '/plant/new': {
      id: '/plant/new'
      path: '/plant/new'
      fullPath: '/plant/new'
      preLoaderRoute: typeof PlantNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/$id/update': {
      id: '/plants/$id/update'
      path: '/update'
      fullPath: '/plants/$id/update'
      preLoaderRoute: typeof PlantsIdUpdateRouteImport
      parentRoute: typeof PlantsIdRoute
    }
    '/plants/$id/care': {
      id: '/plants/$id/care'
      path: '/care'
      fullPath: '/plants/$id/care'
      preLoaderRoute: typeof PlantsIdCareRouteImport
      parentRoute: typeof PlantsIdRoute
    }
  }
}

interface PlantsIdRouteChildren {
  PlantsIdCareRoute: typeof PlantsIdCareRoute
  PlantsIdUpdateRoute: typeof PlantsIdUpdateRoute
}

const PlantsIdRouteChildren: PlantsIdRouteChildren = {
  PlantsIdCareRoute: PlantsIdCareRoute,
  PlantsIdUpdateRoute: PlantsIdUpdateRoute,
}

const PlantsIdRouteWithChildren = PlantsIdRoute._addFileChildren(
  PlantsIdRouteChildren,
)

interface PlantsRouteChildren {
  PlantsIdRoute: typeof PlantsIdRouteWithChildren
}

const PlantsRouteChildren: PlantsRouteChildren = {
  PlantsIdRoute: PlantsIdRouteWithChildren,
}

const PlantsRouteWithChildren =
  PlantsRoute._addFileChildren(PlantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MapRoute: MapRoute,
  NotificationSettingsRoute: NotificationSettingsRoute,
  NotificationsRoute: NotificationsRoute,
  PlantsRoute: PlantsRouteWithChildren,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SpeciesRoute: SpeciesRoute,
  PlantNewRoute: PlantNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
